shopCardData=[
  {
    id: "c1",
    name: "Casual Shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-1.jpg",
  },
  {
    id: "c2",
    name: "Office Shirt",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-2.jpg",
  },
  {
    id: "c3",
    name: "T Shirt",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-3.jpg",
  },
  {
    id: "c4",
    name: "Mens Suit",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-4.jpg",
  },
  {
    id: "c5",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-5.png",
  },
  {
    id: "c6",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-6.png",
  },
  {
    id: "c7",
    name: "black suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-7.png",
  },
  {
    id: "c8",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-8.png",
  },
  {
    id: "c9",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-9.png",
  },
  {
    id: "c10",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-10.png",
  },
  {
    id: "c11",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-11.png",
  },
  {
    id: "c12",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "/Images/img-12.png",
  },
];
